import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={outfit.className}>
          <div className="md:px-20">
            <Header />
            {children}
            <Toaster/>
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
