import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import SocketProvide from "../../providers/SocketProvide";
import Script from "next/script";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doctor Appointment Booking App",
  description: "Generated by create next app",
};

// Add type definition for the props
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <head>
          <Script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-F2MFYWWS6E"
          ></Script>
          <Script id="google-analytics">
            {`
    window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F2MFYWWS6E');
  `}
          </Script>
        </head>
        <body className={outfit.className}>
          <SocketProvide>
            <div className="md:px-20">
              <Header />
              {children}
              <Toaster />
            </div>
            <Footer />
          </SocketProvide>
        </body>
      </html>
    </ClerkProvider>
  );
}
